import { chromium } from "playwright";
const URL = "http://localhost:4400/parity-trio.html?mesh=castle&mode=baked&motion=none&az=60&el=45&cast=1&floor=1&zoom=4";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1800, height: 700 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
page.on("pageerror", (err) => console.log("[pageerror]", err.message));
await page.goto(URL, { waitUntil: "domcontentloaded", timeout: 60000 });
await page.waitForTimeout(12000);
await page.screenshot({ path: "/tmp/parity-trio.png", fullPage: false, timeout: 60000 });
console.log("saved");
await browser.close();
