import type { PresetModel } from "../types";
import {
  GOOGLE_POLY_AMBER_ATTRIBUTION,
  KANGAROOZ_STING_ATTRIBUTION,
  PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION,
  ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  GOOGLE_POLY_FLYING_SAUCER_ATTRIBUTION,
  UTAH_TEAPOT_ATTRIBUTION,
  KENNEY_MINIGOLF_ATTRIBUTION,
  PARFAITUWU_TREE_ATTRIBUTION,
  POLYCSS_GENERATED_PRIMITIVE_ATTRIBUTION,
  POLYCSS_LOCAL_FIXTURE_ATTRIBUTION,
} from "./attributions";
import { GLB_PRESET_FILES, POLY_PIZZA_PRESET_FILES, VOX_PRESET_FILES, OBJ_PRESET_FILES, STL_PRESET_FILES } from "./presetFiles";
import { glbPreset, objPreset, stlPreset, voxPreset } from "./presetBuilders";
import {
  boxPolygons,
  spherePolygons,
  tetrahedronPolygons,
  octahedronPolygons,
  icosahedronPolygons,
  dodecahedronPolygons,
  cylinderPolygons,
  conePolygons,
  torusPolygons,
} from "@layoutit/polycss";

const COLOR = "#ff6644";
const PRIMITIVE_PRESET_DEFAULTS = {
  category: "Primitives",
  kind: "primitive",
  galleryBucket: "Primitives",
  zoom: 0.05,
  rotX: 65,
  rotY: 45,
  attribution: POLYCSS_GENERATED_PRIMITIVE_ATTRIBUTION,
} satisfies Pick<PresetModel, "category" | "kind" | "galleryBucket" | "zoom" | "rotX" | "rotY" | "attribution">;

export const PRESETS: PresetModel[] = [
  {
    id: "primitive-box",
    label: "Box",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => boxPolygons({ size: 100, color: COLOR }),
  },
  {
    id: "primitive-sphere",
    label: "Sphere",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => spherePolygons({ radius: 50, subdivisions: 1, color: COLOR }),
  },
  {
    id: "primitive-tetrahedron",
    label: "Tetrahedron",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => tetrahedronPolygons({ size: 80, color: COLOR }),
  },
  {
    id: "primitive-octahedron",
    label: "Octahedron",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => octahedronPolygons({ center: [0, 0, 0], size: 70, color: COLOR }),
  },
  {
    id: "primitive-icosahedron",
    label: "Icosahedron",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => icosahedronPolygons({ size: 80, color: COLOR }),
  },
  {
    id: "primitive-dodecahedron",
    label: "Dodecahedron",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => dodecahedronPolygons({ size: 80, color: COLOR }),
  },
  {
    id: "primitive-cylinder",
    label: "Cylinder",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => cylinderPolygons({ radius: 40, height: 100, radialSegments: 12, color: COLOR }),
  },
  {
    id: "primitive-cone",
    label: "Cone",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => conePolygons({ radius: 50, height: 100, radialSegments: 12, color: COLOR }),
  },
  {
    id: "primitive-torus",
    label: "Torus",
    ...PRIMITIVE_PRESET_DEFAULTS,
    generatePolygons: () => torusPolygons({ radius: 50, tube: 15, radialSegments: 12, tubularSegments: 16, color: COLOR }),
  },

  {
    id: "chicken",
    label: "Chicken",
    category: "Characters",
    kind: "obj",
    url: "/gallery/obj/chicken.obj",
    mtlUrl: "/gallery/obj/chicken.mtl",
    options: { targetSize: 60, defaultColor: "#cccccc" },
    zoom: 0.15,
    rotX: 74.4,
    rotY: 301.6,
    attribution: GOOGLE_POLY_AMBER_ATTRIBUTION,
  },
  {
    id: "sting",
    label: "Sting Sword (UV-mapped)",
    category: "Weapons",
    kind: "obj",
    url: "/gallery/obj/sting.obj",
    options: {
      targetSize: 60,
      defaultColor: "#cccccc",
      materialTextures: { Sting: "/gallery/obj/sting-diffuse.png" },
    },
    galleryBucket: "Textured",
    zoom: 0.3,
    rotX: 65,
    rotY: 45,
    attribution: KANGAROOZ_STING_ATTRIBUTION,
  },
  {
    id: "cottage",
    label: "Cottage (UV-mapped)",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/cottage.obj",
    options: {
      targetSize: 60,
      defaultColor: "#a0a0a0",
      materialTextures: { cottage_texture: "/gallery/obj/cottage-diffuse.png" },
      includeObjects: ["Cube_Cube.002"],
    },
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  },
  {
    id: "rock1",
    label: "Rock (UV-mapped)",
    category: "Environment",
    kind: "obj",
    url: "/gallery/obj/rock1.obj",
    mtlUrl: "/gallery/obj/rock1.mtl",
    options: { targetSize: 40, defaultColor: "#8b6f47", excludeObjects: ["Plane"] },
    galleryBucket: "Textured",
    zoom: 0.6,
    rotX: 65,
    rotY: 45,
    attribution: PROJECT_CHRONO_OFFROAD_ATTRIBUTION,
  },
  {
    id: "insurgent",
    label: "Ship - Insurgent",
    category: "Vehicles",
    kind: "gltf",
    url: "/gallery/glb/insurgent.gltf",
    options: { targetSize: 60 },
    galleryBucket: "Textured",
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: { ...QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION, tris: 3012 },
  },
  {
    id: "apoc-car",
    label: "Car (GLB)",
    category: "Vehicles",
    kind: "glb",
    url: "/gallery/glb/apocalypse/car.glb",
    options: { targetSize: 60 },
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-barrel",
    label: "Barrel (GLB)",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/barrel.glb",
    options: { targetSize: 50 },
    zoom: 0.5,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-tire",
    label: "Tire (GLB)",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/tire.glb",
    options: { targetSize: 50 },
    zoom: 0.5,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-ground-planks",
    label: "Ground Planks (GLB)",
    category: "Environment",
    kind: "glb",
    url: "/gallery/glb/apocalypse/ground_planks.glb",
    options: { targetSize: 60 },
    zoom: 0.55,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-jerry-can",
    label: "Jerry Can (GLB)",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/jerry_can_with_nozzle.glb",
    options: { targetSize: 50 },
    zoom: 0.5,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-pallet-cluster",
    label: "Pallet Cluster (GLB)",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/pallet_cluster_1.glb",
    options: { targetSize: 60 },
    zoom: 0.45,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-road-barrier",
    label: "Road Barrier (GLB)",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/road_barrier.glb",
    options: { targetSize: 60 },
    zoom: 0.45,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-electric-pole",
    label: "Electric Pole (GLB)",
    category: "Environment",
    kind: "glb",
    url: "/gallery/glb/apocalypse/electric_pole_1.glb",
    options: { targetSize: 70 },
    zoom: 0.35,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-wall-hole",
    label: "Wall with Hole (GLB)",
    category: "Architecture",
    kind: "glb",
    url: "/gallery/glb/apocalypse/wall_1_hole.glb",
    options: { targetSize: 60 },
    zoom: 0.45,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "apoc-spike",
    label: "Spike Barricade (GLB)",
    category: "Objects",
    kind: "glb",
    url: "/gallery/glb/apocalypse/wooden_spike_barricade.glb",
    options: { targetSize: 60 },
    zoom: 0.4,
    rotX: 65,
    rotY: 45,
    attribution: ATOMIC_REALM_POST_APOCALYPTIC_ATTRIBUTION,
  },
  {
    id: "tree",
    label: "Tree",
    category: "Environment",
    kind: "glb",
    url: "/gallery/glb/tree.glb",
    options: { targetSize: 60 },
    zoom: 0.3,
    rotX: 65,
    rotY: 45,
    attribution: PARFAITUWU_TREE_ATTRIBUTION,
  },
  {
    id: "saucer",
    label: "Flying saucer",
    category: "Vehicles",
    kind: "glb",
    url: "/gallery/glb/poly-pizza/flying-saucer.glb",
    options: { targetSize: 60, defaultColor: "#94a3b8" },
    zoom: 0.2,
    rotX: 67,
    rotY: 42.3,
    attribution: GOOGLE_POLY_FLYING_SAUCER_ATTRIBUTION,
  },
  {
    id: "teapot",
    label: "Teapot",
    category: "Objects",
    kind: "obj",
    url: "/gallery/obj/teapot.obj",
    options: { targetSize: 60, defaultColor: "#a3a3a3" },
    zoom: 0.2,
    rotX: 65,
    rotY: 45,
    attribution: UTAH_TEAPOT_ATTRIBUTION,
  },
  {
    id: "castle",
    label: "Castle",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/castle.obj",
    options: { targetSize: 60 },
    zoom: 0.15,
    rotX: 66.9,
    rotY: 68.5,
    attribution: KENNEY_MINIGOLF_ATTRIBUTION,
  },
  {
    id: "coliseum",
    label: "Coliseum",
    category: "Architecture",
    kind: "obj",
    url: "/gallery/obj/coliseum.obj",
    options: { targetSize: 80, palette: ["#c9a876", "#a78760", "#8b6f47", "#6b5538"] },
    zoom: 0.15,
    rotX: 65,
    rotY: 45,
    attribution: POLYCSS_LOCAL_FIXTURE_ATTRIBUTION,
  },
  ...OBJ_PRESET_FILES.map(objPreset),
  ...STL_PRESET_FILES.map(stlPreset),
  ...GLB_PRESET_FILES.map(glbPreset),
  ...POLY_PIZZA_PRESET_FILES.map(glbPreset),
  ...VOX_PRESET_FILES.map(voxPreset),
];
