import type { GalleryPresetFile, ObjGalleryPresetFile } from "../types";
import {
  MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  MINI_MIKES_METRO_MINIS_ATTRIBUTION,
  MONOGON_DESERT_TOWN_ATTRIBUTION,
  MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION,
  MONOGON_COUNTRY_SIDE_ATTRIBUTION,
  MONOGON_CYBERPUNK_CITY_ATTRIBUTION,
  MONOGON_VOXEL_PLANE_ATTRIBUTION,
  MONOGON_VOXEL_MECHAS_ATTRIBUTION,
  MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION,
  SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION,
  GOOGLE_POLY_ASTRONAUT_ATTRIBUTION,
  KHRONOS_AVOCADO_ATTRIBUTION,
  MAGICAVOXEL_TEST_MODELS_ATTRIBUTION,
  OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  OPENHV_VOXELS_ATTRIBUTION,
  FLOOOH_VOXEL_DATA_ATTRIBUTION,
  QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION,
  nasa3dAttribution,
  openGameArtAttribution,
  quaterniusAttribution,
  smithsonianOpenAccessAttribution,
} from "./attributions";

const NASA_GLB_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "nasa/opportunity.glb",
    label: "Mars Rover Opportunity",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/mars-exploration-rover-opportunity-mer-b/",
      3754,
    ),
  },
  {
    file: "nasa/cubesat-1u.glb",
    label: "CubeSat 1U",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Christopher R. Meaney",
      "https://science.nasa.gov/3d-resources/cubesat-1-ru-generic/",
      6063,
    ),
  },
  {
    file: "nasa/tdrs-a.glb",
    label: "Tracking and Data Relay Satellite",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/tracking-and-data-relay-satellites-tdrs-a/",
      2936,
    ),
  },
  {
    file: "nasa/hubble-space-telescope.glb",
    label: "Hubble Space Telescope",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/hubble-space-telescope-a/",
      7670,
    ),
  },
  {
    file: "nasa/international-space-station.glb",
    label: "International Space Station",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/international-space-station-iss-a/",
      6628,
    ),
  },
  {
    file: "nasa/space-shuttle.glb",
    label: "Space Shuttle",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-b/",
      2473,
    ),
  },
  {
    file: "nasa/kepler.glb",
    label: "Kepler Space Telescope",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/kepler-b/",
      372,
    ),
  },
  {
    file: "nasa/mars-global-surveyor.glb",
    label: "Mars Global Surveyor",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/JPL/Eyes on the Solar System",
      "https://science.nasa.gov/3d-resources/mars-global-surveyor/",
      6194,
    ),
  },
  {
    file: "nasa/grace.glb",
    label: "GRACE",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Brian E. Kumanchik; NASA/Christian A. Lopez",
      "https://science.nasa.gov/3d-resources/gravity-recovery-and-climate-experiment-grace-a/",
      3439,
    ),
  },
  {
    file: "nasa/icesat-a.glb",
    label: "ICESat",
    category: "Vehicles",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Ames Research Center",
      "https://science.nasa.gov/3d-resources/ice-clouds-and-land-elevation-satellite-icesat-a/",
      976,
    ),
  },
  {
    file: "nasa/gamma-ray-observatory.glb",
    label: "Gamma Ray Observatory",
    category: "Vehicles",
    attribution: nasa3dAttribution(
      "NASA/Christopher R. Meaney",
      "https://science.nasa.gov/3d-resources/gamma-ray-observatory/",
      4244,
    ),
  },
  {
    file: "nasa/wide-field-planetary-camera.glb",
    label: "Wide Field Planetary Camera",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/wide-field-planetary-camera/",
      224,
    ),
  },
  {
    file: "nasa/crew-lock-bag.glb",
    label: "Crew Lock Bag",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/crew-lock-bag/",
      506,
    ),
  },
  {
    file: "nasa/flight-system-support.glb",
    label: "Flight System Support",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "DigitalSpace Corporation",
      "https://science.nasa.gov/3d-resources/flight-system-support/",
      1292,
    ),
  },
  {
    file: "nasa/space-shuttle-eva-suit.glb",
    label: "EVA Suit",
    category: "Objects",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      6430,
    ),
  },
  {
    file: "nasa/orbiter-docking-system.glb",
    label: "Orbiter Docking System",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      5635,
    ),
  },
  {
    file: "nasa/space-shuttle-external-tank.glb",
    label: "Space Shuttle External Tank",
    category: "Vehicles",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      6326,
    ),
  },
  {
    file: "nasa/solid-rocket-booster.glb",
    label: "Solid Rocket Booster",
    category: "Vehicles",
    galleryBucket: "Textured",
    attribution: nasa3dAttribution(
      "NASA/Johnson Space Center",
      "https://science.nasa.gov/3d-resources/space-shuttle-parts/",
      4136,
    ),
  },
];

const SMITHSONIAN_GLB_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "smithsonian/morse-telegraph-key.glb",
    label: "Morse-Vail Telegraph Key",
    category: "Objects",
    galleryBucket: "Textured",
    attribution: smithsonianOpenAccessAttribution(
      "https://www.si.edu/object/morse-vail-telegraph-key%3Anmah_1096762",
      3600,
    ),
  },
];

export const GLB_PRESET_FILES: GalleryPresetFile[] = [
  { file: "FishAnimated.glb", label: "Fish", category: "Animated" },
  {
    file: "opengameart/animated-pliers.glb",
    label: "Pliers",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 1452),
  },
  {
    file: "opengameart/animated-utility-knife.glb",
    label: "Utility Knife",
    category: "Animated",
    attribution: openGameArtAttribution("LonesomeDucky", "tool-pack-2", 576),
  },
  { file: "AnimatedMushnub.glb", label: "Mushnub", category: "Animated" },
  { file: "AnimatedSnake.glb", label: "Snake", category: "Animated" },
  { file: "Bat.glb", category: "Animals" },
  { file: "Bear.glb", category: "Animals" },
  { file: "Cat.glb", category: "Animals" },
  { file: "Cheetah.glb", category: "Animals" },
  { file: "Deer.glb", category: "Animals" },
  { file: "Dinosaur.glb", category: "Animals" },
  { file: "Dog.glb", category: "Animals" },
  { file: "Dolphin.glb", category: "Animals" },
  { file: "Dragon.glb", category: "Animals" },
  { file: "Duck.glb", category: "Animals" },
  { file: "Elephant.glb", category: "Animals" },
  { file: "Fly.glb", category: "Animals" },
  { file: "Frog.glb", category: "Animals" },
  { file: "Gorilla.glb", category: "Animals" },
  { file: "Hippo.glb", category: "Animals" },
  { file: "Horse.glb", category: "Animals" },
  { file: "Koala.glb", category: "Animals" },
  { file: "Lobster.glb", category: "Animals" },
  { file: "Octopus.glb", category: "Animals" },
  { file: "Owl.glb", category: "Animals" },
  { file: "Pig.glb", category: "Animals" },
  { file: "Poodle.glb", category: "Animals" },
  { file: "Rat.glb", category: "Animals" },
  { file: "Robin.glb", category: "Animals" },
  { file: "Scorpion.glb", category: "Animals" },
  { file: "Shark.glb", category: "Animals" },
  { file: "Snail.glb", category: "Animals" },
  { file: "Wolf.glb", category: "Animals" },
  { file: "Zebra.glb", category: "Animals" },
  { file: "Dump truck.glb", label: "Dump Truck", category: "Vehicles" },
  { file: "Policecar.glb", label: "Police Car", category: "Vehicles" },
  { file: "Taxi.glb", category: "Vehicles" },
  { file: "Truck.glb", category: "Vehicles" },
  ...NASA_GLB_PRESET_FILES,
  {
    file: "model-viewer/astronaut.glb",
    label: "Astronaut",
    category: "Characters",
    galleryBucket: "Textured",
    attribution: GOOGLE_POLY_ASTRONAUT_ATTRIBUTION,
  },
  { file: "Acousticguitar.glb", label: "Guitar (Acoustic)", category: "Instruments" },
  { file: "Electricguitar.glb", label: "Guitar (Electric)", category: "Instruments" },
  { file: "Saxophone.glb", category: "Instruments" },
  { file: "Trumpet.glb", category: "Instruments" },
  { file: "Violin.glb", category: "Instruments" },
  ...SMITHSONIAN_GLB_PRESET_FILES,
  { file: "apple.glb", label: "Apple", category: "Food & Drink" },
  {
    file: "khronos/avocado.glb",
    label: "Avocado",
    category: "Food & Drink",
    galleryBucket: "Textured",
    attribution: KHRONOS_AVOCADO_ATTRIBUTION,
  },
  { file: "BottleChampagne.glb", label: "Champagne Bottle", category: "Food & Drink" },
  { file: "Eggplant.glb", category: "Food & Drink" },
  { file: "Grapes.glb", category: "Food & Drink" },
  { file: "Hot dog.glb", label: "Hot Dog", category: "Food & Drink" },
  { file: "Watermelon.glb", category: "Food & Drink" },
  { file: "Cactus.glb", category: "Environment" },
  { file: "Campfire.glb", category: "Environment" },
  { file: "Drill.glb", category: "Objects" },
  { file: "Globe.glb", category: "Objects" },

  // Medieval Village Pack — used by the /builder Medieval Village scene
  // preset as well as standalone models. All share the same category so
  // they group cleanly in the sidebar.
  { file: "medieval/Bags.glb", category: "Medieval Village" },
  { file: "medieval/Barrel.glb", category: "Medieval Village" },
  { file: "medieval/Bell.glb", category: "Medieval Village" },
  { file: "medieval/Bonfire.glb", category: "Medieval Village" },
  { file: "medieval/Cart.glb", category: "Medieval Village" },
  { file: "medieval/Cauldron.glb", category: "Medieval Village" },
  { file: "medieval/Crate.glb", label: "Medieval Crate", category: "Medieval Village" },
  { file: "medieval/Package.glb", category: "Medieval Village" },
  { file: "medieval/Package-kYvD6QCQRd.glb", label: "Package (Small)", category: "Medieval Village" },
  { file: "medieval/Path Straight.glb", label: "Path Straight", category: "Medieval Village" },
  { file: "medieval/Rocks.glb", category: "Medieval Village" },
  { file: "medieval/Sawmill Saw.glb", label: "Sawmill Saw", category: "Medieval Village" },
  { file: "medieval/Smoke.glb", category: "Medieval Village" },
  { file: "medieval/Well.glb", category: "Medieval Village" },
  { file: "medieval/Window.glb", category: "Medieval Village" },
  { file: "medieval/Window-EY1zrFcme9.glb", label: "Window (Tall)", category: "Medieval Village" },

  // City Kit — used by the /builder City Block scene preset and for
  // standalone placement. Keep a compact Solid gallery set instead of
  // listing every building variant.
  { file: "city/Skyscraper.glb", category: "City Kit" },
  { file: "city/Large Building.glb", label: "Large Building", category: "City Kit" },
  { file: "city/Small Building.glb", label: "Small Building", category: "City Kit" },

  // Urban Pack — cars + street furniture + a few characters.
  // Used by the /builder "City Street" scene plus ad-hoc placement.
  { file: "urban/Road Bits.glb", label: "Road", category: "Urban Pack" },
  { file: "urban/Manhole Cover.glb", label: "Manhole Cover", category: "Urban Pack" },

  { file: "urban/Car.glb", category: "Urban Pack" },
  { file: "urban/SUV.glb", category: "Urban Pack" },
  { file: "urban/Van.glb", category: "Urban Pack" },
  { file: "urban/Pickup Truck.glb", label: "Pickup Truck", category: "Urban Pack" },
  { file: "urban/Bus.glb", label: "City Bus", category: "Urban Pack" },
  { file: "urban/Sports Car.glb", label: "Sports Car", category: "Urban Pack" },
  { file: "urban/Police Car.glb", label: "Police Cruiser", category: "Urban Pack" },
  { file: "urban/Motorcycle.glb", category: "Urban Pack" },
  { file: "urban/Stop sign.glb", label: "Stop Sign", category: "Urban Pack" },
  { file: "urban/Billboard.glb", category: "Urban Pack", galleryBucket: "Textured" },

  { file: "urban/Dumpster.glb", category: "Urban Pack" },
  { file: "urban/Mailbox.glb", category: "Urban Pack" },
  { file: "urban/Fire hydrant.glb", label: "Fire Hydrant", category: "Urban Pack" },
  { file: "urban/Cone.glb", label: "Traffic Cone", category: "Urban Pack" },
  { file: "urban/Box.glb", label: "Urban Box", category: "Urban Pack" },
  { file: "urban/Power Box.glb", label: "Power Box", category: "Urban Pack" },
  { file: "urban/Air conditioner.glb", label: "Air Conditioner", category: "Urban Pack" },
  { file: "urban/ATM.glb", category: "Urban Pack" },
  { file: "urban/Planter & Bushes.glb", label: "Planter & Bushes", category: "Urban Pack" },
  { file: "urban/Man.glb", label: "Urban Man", category: "Urban Pack" },
  { file: "urban/Adventurer.glb", category: "Urban Pack" },
  { file: "urban/Animated Woman.glb", label: "Woman", category: "Urban Pack" },
];

export const POLY_PIZZA_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "poly-pizza/fruit-crate.glb",
    label: "Fruit Crate",
    category: "Food & Drink",
    attribution: {
      creator: "BlenderVoyage",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/aXulVWHOeV",
      tris: 196,
    },
  },
  {
    file: "poly-pizza/pizza-slice.glb",
    label: "Pizza Slice",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/CA4HtaaMJn",
      tris: 392,
    },
  },
  {
    file: "poly-pizza/sheep.glb",
    label: "Sheep",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/C39AUXUUes",
      tris: 610,
    },
  },
  {
    file: "poly-pizza/animated-robot.glb",
    label: "Robot",
    category: "Animated",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/QCm7qe9uNJ",
      tris: 1425,
    },
  },
  {
    file: "poly-pizza/animated-fox-quaternius.glb",
    label: "Fox",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/Bc97C66HKi", 1848),
  },
  {
    file: "poly-pizza/animated-husky.glb",
    label: "Husky",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/wcWiuEqwzq", 1920),
  },
  {
    file: "poly-pizza/animated-shiba-inu.glb",
    label: "Shiba Inu",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/y4wdQpg767", 1950),
  },
  {
    file: "poly-pizza/animated-whale.glb",
    label: "Whale",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/JGFwp6xWgk", 444),
  },
  {
    file: "poly-pizza/animated-shark.glb",
    label: "Shark",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/sZR8AMLMz5", 1310),
  },
  {
    file: "poly-pizza/animated-enemy-small.glb",
    label: "Enemy Small",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/4LjT020LQh", 1572),
  },
  {
    file: "poly-pizza/animated-slime-enemy.glb",
    label: "Slime Enemy",
    category: "Animated",
    attribution: quaterniusAttribution("https://poly.pizza/m/eSLKTsbl7F", 1968),
  },
  {
    file: "poly-pizza/cow.glb",
    label: "Cow",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/5XSc2Fka3F",
      tris: 796,
    },
  },
  {
    file: "poly-pizza/ducky.glb",
    label: "Ducky",
    category: "Animals",
    attribution: {
      creator: "Isa Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/gt2eYOyOvU",
      tris: 604,
    },
  },
  {
    file: "poly-pizza/fish.glb",
    label: "Low Poly Fish",
    category: "Animals",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HkUAXudvBt",
      tris: 233,
    },
  },
  {
    file: "poly-pizza/llama.glb",
    label: "Llama",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/JxVJ9rfWGy",
      tris: 661,
    },
  },
  {
    file: "poly-pizza/pug.glb",
    label: "Pug",
    category: "Animals",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/1gXKv15ik8",
      tris: 644,
    },
  },
  {
    file: "poly-pizza/bucket.glb",
    label: "Bucket",
    category: "Objects",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/tKTttwROq7",
      tris: 532,
    },
  },
  {
    file: "poly-pizza/can.glb",
    label: "Can",
    category: "Objects",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/YnowJvWqxE",
      tris: 428,
    },
  },
  {
    file: "poly-pizza/bread.glb",
    label: "Bread",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/luo9BHRaax",
      tris: 116,
    },
  },
  {
    file: "poly-pizza/cup-tea.glb",
    label: "Cup Tea",
    category: "Food & Drink",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FUSyrlibw0",
      tris: 108,
    },
  },
  {
    file: "poly-pizza/egg-fried.glb",
    label: "Egg Fried",
    category: "Food & Drink",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/NVrB2yd66v",
      tris: 101,
    },
  },
  {
    file: "poly-pizza/rock.glb",
    label: "Low Poly Rock",
    category: "Environment",
    attribution: {
      creator: "Kenney",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cBqdRdLDDL",
      tris: 120,
    },
  },
  {
    file: "poly-pizza/rock-medium.glb",
    label: "Rock Medium",
    category: "Environment",
    galleryBucket: "Textured",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/s1OJ3bBzqc",
      tris: 342,
    },
  },
  {
    file: "poly-pizza/box.glb",
    label: "Cardboard Box",
    category: "Objects",
    attribution: {
      creator: "Kay Lousberg",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/ykZ23x9d6p",
      tris: 32,
    },
  },
  {
    file: "poly-pizza/empty-box.glb",
    label: "Empty Box",
    category: "Objects",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/pZBpmjtvw8",
      tris: 76,
    },
  },
  {
    file: "poly-pizza/animated-human.glb",
    label: "Human",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/c3Ibh9I3udk",
      tris: 1578,
    },
  },
  {
    file: "poly-pizza/character-animated.glb",
    label: "Character",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/DgOCW9ZCRJ",
      tris: 1246,
    },
  },
  {
    file: "poly-pizza/human-dude-guy.glb",
    label: "Human Dude Guy",
    category: "Characters",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/83DpVkzvWk",
      tris: 1151,
    },
  },
  {
    file: "poly-pizza/man.glb",
    label: "Man",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/HMnuH5geEG",
      tris: 1216,
    },
  },
  {
    file: "poly-pizza/rabbit-blond.glb",
    label: "Rabbit Blond",
    category: "Characters",
    attribution: {
      creator: "Quaternius",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/cMsI6FDhNx",
      tris: 1570,
    },
  },
  {
    file: "poly-pizza/arrow.glb",
    label: "Arrow",
    category: "Weapons",
    attribution: {
      creator: "CreativeTrio",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/dZVjrxZdaB",
      tris: 119,
    },
  },
  {
    file: "poly-pizza/sword.glb",
    label: "Sword",
    category: "Weapons",
    attribution: {
      creator: "hat_my_guy",
      license: "CC0 1.0",
      sourceUrl: "https://poly.pizza/m/FvUHJZzy1M",
      tris: 141,
    },
  },
];

function voxFiles(
  files: string[],
  attribution: GalleryPresetFile["attribution"],
): GalleryPresetFile[] {
  return files.map((file) => ({ file, category: "VOX", attribution }));
}

const MINI_MIKES_METRO_MINIS_VOX_FILES: string[] = [
  "alien_bot1.vox",
  "alien_engi1a.vox",
  "alien_eye1a.vox",
  "chr_chef.vox",
  "chr_cop1.vox",
  "chr_hazmat1.vox",
  "chr_janitor.vox",
  "chr_paramedic2.vox",
  "chr_punk.vox",
  "chr_riotcop.vox",
  "chr_scientist.vox",
  "chr_super1.vox",
  "chr_thief.vox",
  "chr_zombie4.vox",
  "mob_cat1.vox",
  "mob_penguin.vox",
  "obj_arcade1.vox",
  "obj_boxingring.vox",
  "obj_busstop.vox",
  "obj_candle.vox",
  "obj_cart1a.vox",
  "obj_container4.vox",
  "obj_pumpkin.vox",
  "piano.vox",
  "scene_checkpoint.vox",
  "scene_coffee.vox",
  "scene_hazmat.vox",
  "scene_protest.vox",
  "scene_zombies.vox",
  "veh_ambulance.vox",
  "veh_cab1.vox",
  "veh_car1.vox",
  "veh_fire.vox",
  "veh_lunch1.vox",
  "veh_mini1.vox",
  "veh_police1.vox",
  "veh_suv1.vox",
  "veh_train.vox",
  "veh_truck1.vox",
];

const MAGICAVOXEL_TEST_MODEL_FILES: string[] = [
  "chr_knight.vox",
];

const OPENGAMEART_BUILDING_VOX_FILES: GalleryPresetFile[] = [
  {
    file: "opengameart-buildings/building-01.vox",
    label: "Building 01",
    category: "VOX",
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/building-02.vox",
    label: "Building 02",
    category: "VOX",
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/tower-01.vox",
    label: "Tower",
    category: "VOX",
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/mini-building-01.vox",
    label: "Small Building 01",
    category: "VOX",
    targetSize: 45,
    zoom: 0.55,
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
  {
    file: "opengameart-buildings/mini-building-02.vox",
    label: "Small Building 02",
    category: "VOX",
    targetSize: 45,
    zoom: 0.55,
    attribution: OPENGAMEART_VOXEL_BUILDINGS_ATTRIBUTION,
  },
];

const OPENHV_VOX_FILES: GalleryPresetFile[] = [
  { file: "openhv/battleship.vox", label: "Battleship", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/dropship.vox", label: "Dropship", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/firetruck.vox", label: "Fire Truck", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/saucer.vox", label: "Saucer", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
  { file: "openhv/turtle.vox", label: "Turtle", category: "VOX", attribution: OPENHV_VOXELS_ATTRIBUTION },
];

const FLOOOH_VOX_FILES: GalleryPresetFile[] = [
  { file: "floooh/cassette.vox", label: "Cassette", category: "VOX", targetSize: 35, zoom: 0.7, attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
  { file: "floooh/kc85-computer.vox", label: "KC85 Computer", category: "VOX", attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
  { file: "floooh/kc85-keyboard.vox", label: "KC85 Keyboard", category: "VOX", targetSize: 35, zoom: 0.6, attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
  { file: "floooh/lcr-c.vox", label: "LCR-C", category: "VOX", targetSize: 45, zoom: 0.5, attribution: FLOOOH_VOXEL_DATA_ATTRIBUTION },
];

export const VOX_PRESET_FILES: GalleryPresetFile[] = [
  {
    file: "AncientCrashSite.vox",
    label: "Ancient Crash Site",
    category: "VOX",
    targetSize: 70,
    zoom: 0.35,
    attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION,
  },
  { file: "army.vox", label: "Army", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "desert.vox", label: "Desert", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "desert2.vox", label: "Desert 2", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "Garden.vox", category: "VOX", attribution: MONOGON_TINY_VOXEL_DUNGEON_ATTRIBUTION },
  { file: "Building03.vox", label: "Desert Building", category: "VOX", attribution: MONOGON_DESERT_TOWN_ATTRIBUTION },
  { file: "HUT.vox", label: "Hut", category: "VOX", attribution: MONOGON_COUNTRY_SIDE_ATTRIBUTION },
  { file: "house.vox", label: "House", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "pyramid.vox", label: "Pyramid", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "skyscraper.vox", label: "Voxel Skyscraper", category: "VOX", attribution: MONOGON_CYBERPUNK_CITY_ATTRIBUTION },
  { file: "Plane_03.vox", label: "Voxel Plane", category: "VOX", attribution: MONOGON_VOXEL_PLANE_ATTRIBUTION },
  { file: "bus.vox", label: "Voxel Bus", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "tank.vox", label: "Tank", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "arachnoid.vox", label: "Arachnoid", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "MechaGolem.vox", label: "Mecha Golem", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "mecha.vox", label: "Mecha", category: "VOX", attribution: MONOGON_VOXEL_MECHAS_ATTRIBUTION },
  { file: "StarMarineTrooper.vox", label: "Star Marine Trooper", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "apple.vox", label: "Voxel Apple", category: "VOX", attribution: SONA_SAR_VOXEL_ANIMALS_ITEMS_ATTRIBUTION },
  { file: "dual.vox", label: "Dual Ship", category: "VOX", attribution: MONOGON_VOXEL_SPACESHIPS_ATTRIBUTION },
  { file: "Treasure.vox", category: "VOX", attribution: MONOGON_ANCIENT_ENVIRONMENT_ATTRIBUTION },
  { file: "tree.vox", label: "Voxel Tree", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  ...OPENGAMEART_BUILDING_VOX_FILES,
  ...OPENHV_VOX_FILES,
  ...FLOOOH_VOX_FILES,
  { file: "chr_robot.vox", label: "Voxel Robot", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "horse.vox", label: "Voxel Horse", category: "VOX", attribution: MAGICAVOXEL_TEST_MODELS_ATTRIBUTION },
  { file: "mob_bear.vox", label: "Voxel Bear", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "obj_campfire.vox", label: "Voxel Campfire", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  { file: "scene_train.vox", label: "Train Scene", category: "VOX", attribution: MINI_MIKES_METRO_MINIS_ATTRIBUTION },
  ...voxFiles(MINI_MIKES_METRO_MINIS_VOX_FILES, MINI_MIKES_METRO_MINIS_ATTRIBUTION),
  ...voxFiles(MAGICAVOXEL_TEST_MODEL_FILES, MAGICAVOXEL_TEST_MODELS_ATTRIBUTION),
];

const ULTIMATE_SPACESHIPS_ROOT = "quaternius/ultimate-spaceships";

export function ultimateSpaceshipPreset(
  slug: string,
  name: string,
  texture: string,
  tris: number,
): ObjGalleryPresetFile {
  return {
    file: `${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${name}.obj`,
    label: `Ship - ${name}`,
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.24,
    attribution: { ...QUATERNIUS_ULTIMATE_SPACESHIPS_ATTRIBUTION, tris },
    options: {
      materialTextures: {
        Texture: `/gallery/obj/${ULTIMATE_SPACESHIPS_ROOT}/${slug}/${texture}`,
      },
    },
  };
}

export const OBJ_PRESET_FILES: ObjGalleryPresetFile[] = [
  {
    file: "opengameart/crate/Box.obj",
    label: "Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("Kutejnikov", "crate-5", 12),
  },
  {
    file: "opengameart/low-poly-car/car.obj",
    label: "Low Poly Car",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.3,
    attribution: openGameArtAttribution("drummyfish", "low-poly-car-3", 228),
  },
  {
    file: "opengameart/wood-crate/woodcrate.obj",
    label: "Wood Crate",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "wood-crate-3d", 284),
  },
  {
    file: "opengameart/broken-stone-slab/stone.obj",
    label: "Broken Stone Slab",
    category: "Environment",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "broken-stone-slab", 186),
  },
  {
    file: "opengameart/frog-guy/frog.obj",
    label: "Frog Guy",
    category: "Characters",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("drummyfish", "frog-guy", 356),
  },
  {
    file: "opengameart/game-cartridge/cartridge.obj",
    label: "Game Cartridge",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("Kutejnikov", "game-cartridge", 432, "CC-BY 4.0"),
  },
  {
    file: "opengameart/fire-extinguisher/extinguisher.obj",
    label: "Fire Extinguisher",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("cron", "fire-extinguisher-2", 818, "CC-BY-SA 4.0"),
  },
  {
    file: "opengameart/keycard/keycard.obj",
    label: "Keycard",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.45,
    attribution: openGameArtAttribution("codeinfernogames", "3d-keycard", 20),
  },
  {
    file: "opengameart/pirate-coin/pirate-coin.obj",
    label: "Pirate Coin",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("acasas", "3d-pirate-coin", 624, "CC-BY 3.0"),
  },
  {
    file: "opengameart/perfume-bottle/perfume.obj",
    label: "Perfume Bottle",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("PantherOne", "perfume-bottle-persian", 196, "CC-BY 3.0"),
  },
  {
    file: "opengameart/grandfather-clock/grandfather-clock.obj",
    label: "Grandfather Clock",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("GGBotNet", "grandfather-clock-3d", 106, "CC-BY 4.0"),
  },
  {
    file: "opengameart/old-book/old-book.obj",
    label: "Old Book",
    category: "Objects",
    galleryBucket: "Textured",
    zoom: 0.4,
    attribution: openGameArtAttribution("GGBotNet", "old-bible-3d", 60, "CC-BY 4.0"),
  },
  {
    file: "opengameart/haunted-house/hauntedhouse.obj",
    label: "Haunted House",
    category: "Buildings",
    galleryBucket: "Textured",
    zoom: 0.35,
    attribution: openGameArtAttribution("naovia", "haunted-house", 377),
  },
  {
    file: "opengameart/biplane/biplane.obj",
    label: "Low Poly Biplane",
    category: "Vehicles",
    galleryBucket: "Textured",
    zoom: 0.25,
    attribution: openGameArtAttribution("mfep", "low-poly-biplane", 668),
  },
  ultimateSpaceshipPreset("challenger", "Challenger", "Challenger_Green.png", 1748),
  ultimateSpaceshipPreset("executioner", "Executioner", "Executioner_Blue.png", 3388),
  ultimateSpaceshipPreset("omen", "Omen", "Omen_Orange.png", 1426),
  ultimateSpaceshipPreset("pancake", "Pancake", "Pancake_Orange.png", 2688),
  ultimateSpaceshipPreset("spitfire", "Spitfire", "Spitfire_Red.png", 3512),
  ultimateSpaceshipPreset("zenith", "Zenith", "Zenith_Red.png", 2152),
  {
    file: "quaternius/nature/Lilypad.obj",
    label: "Lilypad",
    category: "Environment",
    zoom: 0.45,
    attribution: quaterniusAttribution("https://quaternius.com/packs/ultimatenature.html", 372),
  },
  {
    file: "quaternius/dungeon/Chest_gold.obj",
    label: "Treasure Chest",
    category: "Objects",
    zoom: 0.4,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 436),
  },
  {
    file: "quaternius/dungeon/Torch.obj",
    label: "Torch",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 518),
  },
  {
    file: "quaternius/dungeon/Candelabrum.obj",
    label: "Candelabrum",
    category: "Objects",
    zoom: 0.35,
    attribution: quaterniusAttribution("https://quaternius.com/packs/medievaldungeon.html", 636),
  },
];
