import { describe, expect, it } from "vitest";
import * as world from "./index";

const v1RuntimeExports = [
  "PolyWorldBspError",
  "PolyWorldChunkTreeError",
  "PolyWorldDocumentError",
  "PolyWorldDomRegistry",
  "PolyWorldDomRegistryError",
  "PolyWorldTopologyError",
  "adaptPolyWorldBspDebugSnapshot",
  "adaptPolyWorldChunkStreamingDebugSnapshot",
  "adaptPolyWorldDebugSnapshot",
  "adaptPolyWorldDomApplyDebugSnapshot",
  "adaptPolyWorldPlanDebugSnapshot",
  "adaptPolyWorldPortalDebugSnapshot",
  "adaptPolyWorldPortalFlowDebugSnapshot",
  "applyPolyWorldDomPlan",
  "auditPolyWorldProfileArtifactProof",
  "bakePolyWorldBspPvs",
  "certifyPolyWorldBspTopology",
  "collectPolyWorldElementLayers",
  "compilePolyWorldBrushBsp",
  "compilePolyWorldBsp",
  "compilePolyWorldPolygonBsp",
  "createPolyWorldBspDebugSnapshot",
  "createPolyWorldBspPvsIndex",
  "createPolyWorldBspTree",
  "createPolyWorldChunkGraphFromTree",
  "createPolyWorldChunkStreamingDebugSnapshot",
  "createPolyWorldChunkTree",
  "createPolyWorldDebugSnapshot",
  "createPolyWorldDocument",
  "createPolyWorldDomApplyDebugSnapshot",
  "createPolyWorldDomRegistry",
  "createPolyWorldPlanDebugSnapshot",
  "createPolyWorldPortalDebugSnapshot",
  "createPolyWorldPortalFlowDebugSnapshot",
  "createPolyWorldProfileArtifactBundle",
  "createPolyWorldProfileArtifactBundleEntry",
  "createPolyWorldProfileArtifactProof",
  "createPolyWorldProfileFrameSummary",
  "createPolyWorldResourceLoadSet",
  "createPolyWorldResourceReadinessGuards",
  "createPolyWorldState",
  "createPolyWorldTopology",
  "createPolyWorldTopologyCapabilityContract",
  "decodePolyWorldBspPvsLeafIds",
  "decodePolyWorldBspPvsPortalIds",
  "diffPolyWorldIds",
  "diffPolyWorldState",
  "expandPolyWorldSelectionElementRelations",
  "planPolyWorldBspVisibilityFrame",
  "planPolyWorldChunkStreamingFrame",
  "planPolyWorldElementSet",
  "planPolyWorldLayers",
  "planPolyWorldPortalFlowFrame",
  "planPolyWorldPortalFrame",
  "planPolyWorldTransition",
  "resolvePolyWorldBspBakedPvs",
  "resolvePolyWorldBspLeaf",
  "resolvePolyWorldBspPvs",
  "resolvePolyWorldBspViewPvs",
  "resolvePolyWorldBspViewSurfaceElements",
  "resolvePolyWorldBspVisibility",
  "resolvePolyWorldChunkTreeTraversal",
  "resolvePolyWorldElementRelations",
  "resolvePolyWorldElementSubtree",
  "resolvePolyWorldElements",
  "resolvePolyWorldPortalActivity",
  "resolvePolyWorldPortalFlow",
  "resolvePolyWorldRegionByPoint",
  "resolvePolyWorldRegionSelectionKeys",
  "resolvePolyWorldSpatialElementRole",
  "resolvePolyWorldSpatialElementVisibility",
  "selectPolyWorldBspPvs",
  "selectPolyWorldBspViewPvs",
  "selectPolyWorldChunkStreaming",
  "selectPolyWorldChunkStreamingState",
  "selectPolyWorldChunkWindow",
  "selectPolyWorldElementsByPurpose",
  "selectPolyWorldPortalRegions",
  "snapshotPolyWorldState",
  "summarizePolyWorldBspTopologyProof",
  "summarizePolyWorldChunkTree",
  "summarizePolyWorldResourceReadiness",
  "summarizePolyWorldSpatialElementRoles",
  "tracePolyWorldBspViewPvs",
  "validatePolyWorldBrushBspInput",
  "validatePolyWorldBspCompileInput",
  "validatePolyWorldBspTree",
  "validatePolyWorldChunkTree",
  "validatePolyWorldDocument",
  "validatePolyWorldDomRecord",
  "validatePolyWorldPolygonBspInput",
  "validatePolyWorldTopology",
] as const;

describe("public runtime API", () => {
  it("keeps the V1 runtime export surface explicit", () => {
    expect(Object.keys(world).sort()).toEqual([...v1RuntimeExports].sort());
  });

  it("keeps stale topology naming out of runtime exports", () => {
    const staleNames = Object.keys(world).filter((name) => /(?:Object|Member|Cell)/.test(name));

    expect(staleNames).toEqual([]);
  });
});
