// @layoutit/polycss-react — React bindings for the polycss CSS-based polygon mesh
// rendering engine.
//
// Public exports define the supported React package surface. Anything not
// exported here is an implementation detail.

// ── Components & hooks ─────────────────────────────────────────────────
export {
  PolyPerspectiveCamera,
  PolyOrthographicCamera,
  PolyCamera,
  usePolyCamera,
  PolyCameraContext,
  useCameraContext,
} from "./camera";
export type {
  PolyPerspectiveCameraProps,
  PolyOrthographicCameraProps,
  PolyCameraProps,
  UseCameraOptions,
  UseCameraResult,
  PolyCameraContextValue,
} from "./camera";

export { PolyScene, PolyMesh, PolyIframe, PolyGround, usePolySceneContext, usePolyMesh, findPolyMeshHandle, pointInMeshElement, findMeshUnderPoint, usePolyMaterial } from "./scene";
export type {
  PolySceneProps,
  PolyMeshProps,
  PolyIframeProps,
  PolyGroundProps,
  UseSceneContextOptions,
  UseSceneContextResult,
  UseMeshResult,
  UseMeshOptions,
  PolyMeshHandle,
  PolyPointerEvent,
  PolyMouseEvent,
  PolyWheelEvent,
  PolyEventHandler,
  InteractionProps,
  PolyRenderStrategy,
  PolyRenderStrategiesOption,
} from "./scene";

export { Poly } from "./shapes";
export type { PolyProps, TransformProps, DOMPassthroughProps } from "./shapes";
export {
  PolyBox,
  PolyPlane,
  PolyRing,
  PolyOctahedron,
  PolySphere,
  PolyTetrahedron,
  PolyIcosahedron,
  PolyDodecahedron,
  PolyCylinder,
  PolyCone,
  PolyTorus,
} from "./shapes";
export type {
  PolyBoxProps,
  PolyPlaneProps,
  PolyRingProps,
  PolyOctahedronProps,
  PolySphereProps,
  PolyTetrahedronProps,
  PolyIcosahedronProps,
  PolyDodecahedronProps,
  PolyCylinderProps,
  PolyConeProps,
  PolyTorusProps,
} from "./shapes";

export { PolyFirstPersonControls, PolyOrbitControls, PolyMapControls, PolyTransformControls } from "./controls";
export type {
  PolyFirstPersonControlsProps,
  PolyFirstPersonControlsOptions,
  PolyFirstPersonControlsHandle,
  PolyOrbitControlsProps,
  PolyOrbitControlsCamera,
  PolyMapControlsProps,
  PolyMapControlsCamera,
  PolyControlsAnimateOptions,
  PolyControlsCamera,
  SharedControlsProps,
  PolyTransformControlsProps,
  PolyTransformControlsObject,
  PolyTransformControlsObjectChangeEvent,
} from "./controls";

export { PolySelect, usePolySelect, usePolySelectionApi } from "./select";
export type { PolySelectProps, PolySelectionApi } from "./select";

export { PolyAxesHelper, PolyDirectionalLightHelper } from "./helpers";
export type {
  PolyAxesHelperProps,
  PolyDirectionalLightHelperProps,
} from "./helpers";

export { injectPolyBaseStyles } from "./styles";

export { collectPolyRenderStats } from "./renderStats";
export type {
  PolyRenderStats,
  PolyRenderStatsOptions,
  PolyRenderSurfaceLeafCounts,
} from "./renderStats";

export { usePolyAnimation } from "./animation/usePolyAnimation";
export type { UsePolyAnimationResult } from "./animation/usePolyAnimation";

// ── Re-exports from @layoutit/polycss-core for convenience ──────────────────
export type {
  Vec2,
  Vec3,
  Polygon,
  PolyMaterial,
  PolyDirectionalLight,
  PolyAmbientLight,
  PolyTextureLightingMode,
  MeshResolution,
  ParseAnimationClip,
  ParseAnimationController,
  ParseResult,
  PolyAnimationClip,
  PolyAnimationAction,
  PolyAnimationMixer,
  PolyAnimationTarget,
  LoopMode,
  ObjParseOptions,
  GltfParseOptions,
  MtlParseResult,
  NormalizeResult,
  ParsedColor,
  TextureTriangle,
  PolygonFace,
  SceneBbox,
  SceneContext,
  SceneContextBuildArgs,
  SceneContextBuildResult,
  CameraState,
  CameraHandle,
  CameraStyleInput,
  AutoRotateOption,
  AutoRotateConfig,
  AxesHelperOptions,
  BoxFace,
  BoxFaceOptions,
  BoxPolygonsOptions,
  ArrowPolygonsOptions,
  RingPolygonsOptions,
  OctahedronPolygonsOptions,
  TetrahedronPolygonsOptions,
  IcosahedronPolygonsOptions,
  DodecahedronPolygonsOptions,
  CylinderPolygonsOptions,
  ConePolygonsOptions,
  TorusPolygonsOptions,
  PlanePolygonsOptions,
  LoadMeshOptions,
  VoxParseOptions,
  StlParseOptions,
  ParseStlColor,
  ParseStlSolid,
  ParseStlTopology,
  SolidTextureSampleOptions,
  TexturePaintMetrics,
  TexturePaintMetricsOptions,
  CoverPlanarPolygonsOptions,
  CullInteriorOptions,
  SeamFacetSplitCandidate,
  SeamFacetSplitCandidateReason,
  SeamFacetSplitOptions,
  SeamFacetSplitReport,
  SeamOverlapCandidate,
  SeamOverlapCandidateKind,
  SeamOverlapDiagnostics,
  SeamOverlapOptions,
  CameraCullNormalGroup,
  CameraCullRotation,
  OptimizeMeshPolygonsOptions,
  OptimizeMeshParseResultOptions,
  OptimizeAnimatedMeshPolygonsOptions,
  SimplifyTriangleMeshPolygonsOptions,
  PolyMeshTransformInput,
} from "@layoutit/polycss-core";
export {
  CAMERA_BACKFACE_CULL_EPS,
  VOXEL_CAMERA_CULL_AXIS_EPS,
  VOXEL_CAMERA_CULL_NORMAL_LIMIT,
  normalizePolygons,
  mergePolygons,
  coverPlanarPolygons,
  optimizeMeshPolygons,
  optimizeMeshParseResult,
  simplifyTriangleMeshPolygons,
  repairMeshSeams,
  seamFacetSplitPolygons,
  seamFacetSplitReport,
  seamOverlapDiagnostics,
  seamOverlapPolygons,
  seamOverlapReport,
  cullInteriorPolygons,
  cameraCullNormalGroups,
  cameraCullNormalGroupsFromPolygons,
  cameraCullNormalKey,
  cameraCullVisibleSignature,
  cameraFacingDepth,
  isAxisAlignedSurfaceNormal,
  isVoxelCameraCullableNormalGroups,
  normalFacesCamera,
  polygonCssSurfaceNormal,
  polygonFacesCamera,
  parseObj,
  parseMtl,
  parseGltf,
  parseStl,
  bakeSolidTextureSamples,
  bakeSolidTextureSampledPolygons,
  loadMesh,
  createIsometricCamera,
  parseVox,
  polygonFaces,
  computeTexturePaintMetrics,
  computeShapeLighting,
  parseColor,
  parsePureColor,
  parseHexColor,
  parseRgbColor,
  formatColor,
  clampChannel,
  shadeColor,
  rotateVec3,
  inverseRotateVec3,
  axesHelperPolygons,
  boxPolygons,
  arrowPolygons,
  ringPolygons,
  octahedronPolygons,
  tetrahedronPolygons,
  icosahedronPolygons,
  dodecahedronPolygons,
  cylinderPolygons,
  conePolygons,
  torusPolygons,
  planePolygons,
  buildSceneContext,
  buildPolyMeshTransform,
  buildPolySceneTransform,
  computeSceneBbox,
  BASE_TILE,
  DEFAULT_CAMERA_STATE,
  DEFAULT_PROJECTION,
  normalizeInvertMultiplier,
  createPolyAnimationMixer,
  optimizeAnimatedMeshPolygons,
  DEFAULT_SEAM_FACET_SPLIT_OPTIONS,
  DEFAULT_SEAM_OVERLAP_OPTIONS,
  LoopOnce,
  LoopRepeat,
  LoopPingPong,
  cssDistanceToWorld as polyCssDistanceToWorld,
  cssPositionToWorld as polyCssPositionToWorld,
  worldDistanceToCss as worldDistanceToPolyCss,
  worldDirectionToCss as worldDirectionToPolyCss,
  worldPositionToCss as worldPositionToPolyCss,
} from "@layoutit/polycss-core";
